name: Build and Deploy

on:
  push:
    branches:
      - Chris-devops-GHA-ci
  pull_request:
    branches:
      - Chris-devops-GHA-ci

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the Web repository (Main repo)
      - name: Checkout Web repository
        uses: actions/checkout@v4
        with:
          repository: EZPZ-OS/EZPZOS.Web
          ref: Chris-devops-GHA-ci

      # Step 2: Checkout the Core repository (Dependency)
      - name: Checkout Core repository
        uses: actions/checkout@v4
        with:
          repository: EZPZ-OS/EZPZOS.Core
          token: ${{ secrets.GH_TOKEN }}  # Use the GH_TOKEN to authenticate and checkout Core
          path: temp/EZPZOS.Core  # Checkout Core into a temporary path

      # Move Core to be on the same level as Web
      - name: Move Core directory
        run: |
          mv temp/EZPZOS.Core EZPZOS.Core
          ls -alh  # List to verify the structure

      # Step 3: Install dependencies and build Core
      - name: Install and build Core
        working-directory: ./EZPZOS.Core
        run: |
          npm install
          npm run build
    
      # Step 4: List Web node_modules to verify Core is linked
      # - name: Verify ezpzos in node_modules
      #   working-directory: .
      #   run: ls -l node_modules/ez*

      # Step 5: Install dependencies and build Web (after Core is built)
      - name: Install and build Web
        # working-directory: ./EZPZOS.Web
        run: |
          npm install
          npm run build



