name: Build and Deploy

on:
  push:
    branches:
      - Chris-devops-GHA-ci
  pull_request:
    branches:
      - Chris-devops-GHA-ci

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Web repository
        uses: actions/checkout@v4
        with:
          repository: EZPZ-OS/EZPZOS.Web
          ref: Chris-devops-GHA-ci
          
      - name: Checkout Core repository
        uses: actions/checkout@v4
        with:
          repository: EZPZ-OS/EZPZOS.Core
          token: ${{ secrets.GH_TOKEN }}  # Use the GH_TOKEN to authenticate and checkout Core
          path: EZPZOS.Core  # This creates a directory at the root of the workspace

      - name: Install and build Core
        working-directory: ./EZPZOS.Core
        run: |
          npm install
          npm run build

      - name: Set Core build status
        id: core_build_status
        run: echo "CORE_BUILD_STATUS=${{ job.status }}" >> $GITHUB_ENV  # Store Core build status in an environment variable

      - name: Copy Core Directory to Correct Location
        run: |
          cp -r EZPZOS.Core /home/runner/work/EZPZOS.Web/EZPZOS.Core

      - name: Install and build Web
        run: |
          npm install
          npm run build

      - name: Set Web build status
        id: web_build_status
        run: echo "WEB_BUILD_STATUS=${{ job.status }}" >> $GITHUB_ENV  # Store Web build status in an environment variable

      - name: Output Core and Web build statuses
        run: |
          echo "Core Build Status: $CORE_BUILD_STATUS"
          echo "Web Build Status: $WEB_BUILD_STATUS"
