name: Build and Deploy

on:
  push:
    branches:
      - Chris-devops-GHA-ci
  pull_request:
    branches:
      - Chris-devops-GHA-ci

jobs:
  build-Web:
    # needs: build-Core
    # if: ${{ github.repository == 'EZPZ-OS/EZPZOS.Web' && needs.build-Core.outputs.Core_build_status == 'success' }}
    runs-on: ubuntu-latest
    outputs:
      Web_build_status: ${{ steps.set_web_status.outputs.status }}
    steps:
      - name: Checkout Web repository
        uses: actions/checkout@v4
        with:
          repository: EZOZ-OS/EZPZOS.Web
          ref: Chris-devops-GHA-ci

      - name: Set up environment with GitHub Token
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Access token from secrets
        run: echo "GitHub Token available"

      - name: Install and build Web
        id: install_build_web
        run: |
          npm install
          npm run build

      - name: Set Web build status
        id: set_web_status
        run: echo "status=${{ job.status }}" >> $GITHUB_OUTPUT


